FROM ubuntu:20.04

WORKDIR /app

RUN apt-get update
RUN apt-get install -y python3-pip

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python3", "-u", "./main.py" ]
